

export const licenseKey='ewogICJmb3JtYXQiOiAxLAogICJjdXN0b21lcklkIjogImZlNGJjOWI4LThjNWYtNDA3My1iYWNlLWZlYjQzZjBlMThlZiIsCiAgIm1heFZlcnNpb25BbGxvd2VkIjogMjQyCn0=.k8x0MMUpFdZk2QgGOnfzcLZFQSSffwb5on8cd5TAgouHc1jPUysXUFjdAq5dpoULzVOy3oC7WxNcZddmDawiJVGF4lFl/5klmKauIF7pawtMbPeoYJZHHvG3WWPaT7TcpYwLxA=='